### ISSUE TITLE
IOS Light (and IOS Dark) theme both not changing Slider Cards theme

### ISSUE THREAD

**Issue by massimoha** [JuanMTech/ios_light_mode_theme#4]
Hi,

I have a bunch of themes installed and have noticed that both the IOS Light and IOS Dark themes do not change any of the 'Slider Button Cards' (https://github.com/custom-cards/slider-button-card/releases) that I have on various pages.  Some of my themes do change these cards to thier theme and others dont.

I thought I would just write to you to let you know that this isnt working on both of these themes. I also do not know if the creator of the Slider Button Card needs to update something to work with your Themes, or if you might need to make a small change to get these cards to change to other themes.

I really love your IOS Light theme and want to use it during the daytime but these sliders cards not changing to the theme so i haven't been able to use it yet.

- I have everything updated to the current versions on both my WIndows PC and Samsung Tablets
- The behaviour is identical on both my PC and Samsung Tablet
- This behaviour has been the same since I started using the Slider Button Card about 4 mths ago, irregardless of all updates and versions.

![Slider Cards not changing theme](https://user-images.githubusercontent.com/111345084/202946035-01aed634-92d2-42f9-8cf5-247e2193db69.PNG)

**Comment by JuanMTech** [comment]
The options to use the correct colors would need to be added. You can check on the custom card repo for the options to add.
